# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

# The Default Profile
[default]
auto_detect_solc = true
# Increase optimizer_runs
optimizer = true
optimizer_runs = 1_000
# Fuzz more than the default 256
fuzz_runs = 1_000
# Configure remappings
remappings = [
  "@ds-test=lib/ds-test/src/",
]

# Extreme Fuzzing CI Profile :P
[ci]
fuzz_runs = 100_000
